run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - prealloc
    - unconvert

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
